SRCS_DIR = src
OBJS_DIR = objs

SRCS_FILES = main Bureaucrat AForm PresidentialPardonForm RobotomyRequestForm ShrubberyCreationForm
SRCS = $(addsuffix .cpp,${SRCS_FILES})
OBJS = ${addprefix ${OBJS_DIR}/, ${SRCS:.cpp=.o}}
DEPS = ${OBJS:.o=.d}